# build and deploy containerapps to azure with oidc federated credentials

name: Build and deploy containerapps

# set permissions for workflow
permissions:
  id-tokens: write


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
      #login to azure with oidc
      


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 

