name: Trigger auto deployment for queuereader

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'queuereaderapp/**'
    - '.github/workflows/queuereader-AutoDeployTrigger-0f9d2e9d-920b-4af8-b3f1-cdaf6391d085.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: hf73telappacr.azurecr.io
          username: ${{ secrets.QUEUEREADER_REGISTRY_USERNAME }}
          password: ${{ secrets.QUEUEREADER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hf73telappacr.azurecr.io/queuereader:${{ github.sha }}
          file: ./queuereaderapp/Dockerfile
          context: ./queuereaderapp/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n queuereader -g telapp-rg --server hf73telappacr.azurecr.io --username  ${{ secrets.QUEUEREADER_REGISTRY_USERNAME }} --password ${{ secrets.QUEUEREADER_REGISTRY_PASSWORD }}
            az containerapp update -n queuereader -g telapp-rg --image hf73telappacr.azurecr.io/queuereader:${{ github.sha }}
